### ISSUE TITLE
Compile kitinerary-extractor on arm64

### ISSUE THREAD

**Issue by alex9434** [MCMic/workflow_kitinerary#62]
Hello, the encl. kitinerary-extractor is for x64 only. Looking at https://invent.kde.org/pim/kitinerary I had a hard time figuring out, how to compile kitinerary-extractor only. Could you kindly share your approach so that I do not have to re-invent the wheel?

**Comment by MCMic** [comment]
Hum, I’m sorry it’s not that clear for me either. See https://invent.kde.org/vkrause/kitinerary-static-build/-/issues/1#note_597789

**Comment by alex9434** [comment]
Any update on this? The instruction mentioned at the above link are not at all clear to me. Or could you kindly add an arm64 executable in future releases of the file?

**Comment by come-nc** [comment]
The binary I ship is from christophwurst/kitinerary-bin.
You can open a request there, but I think it will be easier to install kitinerary yourself on your system.
You can see here it will be preferred to the shipped version: https://github.com/MCMic/workflow_kitinerary/blob/main/lib/Operation.php#L72
